QsAdmin/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QsAdmin.Models;
using Microsoft.AspNet.Identity;
using System.Text;
using WebGrease.Css.Extensions;

namespace QsAdmin.Controllers
{
    public class DealsController : QsAdminController
    {
        private DealManager m = new DealManager();

        public ActionResult Index(int? seachFlag, int? year, int? month, bool? kanryo, string keyword, int? endDealId)
        {
            SeachCondition condition = new SeachCondition(year, month, kanryo, keyword);

            if (Session["DealSearch"] != null && seachFlag == null)
            {
                condition = (SeachCondition)Session["DealSearch"];
            }

            // 完了
            m.EndDeal(endDealId);

            // 取引リスト取得
            List<DealViewModel> deals = m.GetDealList(condition);
            Session["DealSearch"] = condition;

            ViewBag.year = m.GetYearOptions(condition.Year);
            ViewBag.month = m.GetMonthOptions(condition.Month);
            ViewBag.keyword = condition.Keyword;
            ViewBag.Kanryo = condition.Kanryo;

            return View(deals.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        private List<SelectListItem> getCustomerList(string id)
        {
            var list = from c in db.Customers
                       where c.DeleteFlag == false
                       orderby c.GroupName
                       select new SelectListItem
                       {
                           Value = c.CustomerId,
                           Text = c.CustomerShortName,
                           Selected = id != null ? c.CustomerId == id : false
                       };

            return list.ToList();
        }

        public ActionResult Create()
        {
            ViewBag.CustomerId = getCustomerList(null);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName");

            Deal deal = new Deal();

            deal.ReceptionDate = DateTime.Now;
            // 単価は現状ほぼ300円
            deal.Price = 300;
            deal.Number = 0;

            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                deal.AccountId = User.Identity.GetUserId();

                db.Deals.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);

            // 完了日時と計上年月をセット
            if (deal.EndDate == null)
            {
                deal.EndDate = DateTime.Now;
                deal.KeijoTsuki = deal.GetKeijoTsuki();
            }

            if (deal == null)
            {
                return HttpNotFound();
            }

            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName", deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Copy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);

            if (string.IsNullOrEmpty(deal.KeijoTsuki))
            {
                deal.KeijoTsuki = deal.GetKeijoTsuki();
            }

            if (deal == null)
            {
                return HttpNotFound();
            }

            ViewBag.AccountId = new SelectList(db.Users, "Id", "Email", deal.AccountId);
            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Copy([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Deals.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountId = new SelectList(db.Users, "Id", "Email", deal.AccountId);
            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Deal deal = db.Deals.Find(id);
            db.Deals.Remove(deal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 月別売上表示
        /// </summary>
        /// <returns></returns>
        public ActionResult Report(string year, string month, int? range)
        {
            if (string.IsNullOrEmpty(year))
            {
                year = DateTime.Now.Year.ToString();
            }
            if (string.IsNullOrEmpty(month))
            {
                month = DateTime.Now.Month.ToString();
            }
            if (range == null)
            {
                range = 12;
            }

            string date = year + "/" + month + "/01";
            DateTime dateEnd = DateTime.Parse(date);
            DateTime dateStart = DateTime.Parse(date).AddMonths(((int)range - 1) * -1);

            var reports = db.Database.SqlQuery<ReportViewModel>(""
                + " select"
                + "   a.KeijoTsuki as Nengetsu,"
                + "   sum(a.Number) as Number,"
                + "   sum(a.Price * a.Number) as HontaiGaku,"
                + "   sum((a.Price * a.Number) * 0.08) as ShohizeiGaku,"
                + "   sum((a.Price * a.Number) + ((a.Price * a.Number) * 0.08)) as Uriage"
                + " from"
                + "   Deals a"
                + " where"
                + "   a.KeijoTsuki >= '" + dateStart.ToString("yyyy/MM") + "'"
                + "   and a.KeijoTsuki <= '" + dateEnd.ToString("yyyy/MM") + "'"
                + " group by"
                + "   a.KeijoTsuki"
                + " order by"
                + "   a.KeijoTsuki"
                );

            List<ReportViewModel> reportView = reports.ToList();

            ViewBag.year = m.GetYearOptions(int.Parse(year));
            ViewBag.month = m.GetMonthOptions(int.Parse(month));

            return View(reportView);
        }



        public ActionResult Seikyu(string year, string month)
        {
            if (string.IsNullOrEmpty(year))
            {
                year = DateTime.Now.Year.ToString();
            }
            if (string.IsNullOrEmpty(month))
            {
                month = DateTime.Now.Month.ToString();
            }

            ViewBag._Year = year;
            ViewBag._Month = month;

            var seikyus = FindSeikyuView(year, month);

            ViewBag.year = m.GetYearOptions(DateTime.Now.Year);
            ViewBag.month = m.GetMonthOptions(DateTime.Now.Month);

            return View(seikyus);
        }

        public IEnumerable<SeikyuViewModel> FindSeikyuView(string year, string month)
        {
            string pYear = DateTime.Now.Year.ToString();
            string pMonth = DateTime.Now.Month.ToString();

            if (!string.IsNullOrEmpty(year))
            {
                pYear = year;
            }
            if (!string.IsNullOrEmpty(month))
            {
                pMonth = month;
            }

            string keijoTsuki = pYear + "/" + pMonth.PadLeft(2, '0');

            var seikyus = db.Database.SqlQuery<SeikyuViewModel>(""
                + " select"

QsAdmin/Controllers/ToDoController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QsAdmin.Models;

namespace QsAdmin.Controllers
{
    public class ToDosController : QsAdminController
    {
        private ToDoManager m = new ToDoManager();

        public ActionResult Index(int? kanryoToDoId, int? returnToDoId)
        {
            // 完了
            m.EndToDo(kanryoToDoId);

            // 未完了に戻す
            m.ReturnToDo(returnToDoId);

            ToDoView view = new ToDoView();

            // 未完了ToDo取得
            view.MikanryoToDo = m.GetToDoList();

            // 完了ToDo取得（7日前に完了したものまで）
            view.KanryoToDo = m.GetKanryoToDoList(DateTime.Now.AddDays(-7));

            return View(view);
        }

        public ActionResult ToDoViewKanryo()
        {
            // 完了ToDo取得（全て）
            List<KanryoToDoView> toDo = m.GetKanryoToDoList(DateTime.MinValue);

            return View(toDo);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo ToDoData = db.ToDos.Find(id);
            if (ToDoData == null)
            {
                return HttpNotFound();
            }
            return View(ToDoData);
        }

        public ActionResult Create()
        {
            ToDo ToDo = new ToDo()
            {
                AccountId = User.Identity.GetUserId()
            };

            ViewBag.TantoshaId = new SelectList(db.Users, "Id", "AccountName");

            return View(ToDo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AccountId,Title,Description,TantoshaId,ShimekiriDate,KanryoDate")] ToDo ToDoData)
        {
            if (ModelState.IsValid)
            {
                db.ToDos.Add(ToDoData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TantoshaId = new SelectList(db.Users, "Id", "AccountName");

            return View(ToDoData);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo ToDoData = db.ToDos.Find(id);
            if (ToDoData == null)
            {
                return HttpNotFound();
            }

            ViewBag.TantoshaId = new SelectList(db.Users, "Id", "AccountName");

            return View(ToDoData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AccountId,Title,Description,TantoshaId,ShimekiriDate,KanryoDate")] ToDo ToDoData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ToDoData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TantoshaId = new SelectList(db.Users, "Id", "AccountName");

            return View(ToDoData);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo ToDoData = db.ToDos.Find(id);
            if (ToDoData == null)
            {
                return HttpNotFound();
            }
            return View(ToDoData);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToDo ToDoData = db.ToDos.Find(id);
            db.ToDos.Remove(ToDoData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    internal class ButtonAttribute : Attribute
    {
    }
}

QsAdmin/Views/Shared/_Layout.cshtml
@using QsAdmin.Models;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Q'sAdmin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href=@Url.Action("Index", "Home") class="site_title"><i class="fa fa-apple"></i> <span>Q's Admin</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a href=@Url.Action("Index", "Home")><i class="fa fa-home"></i> Home </a>
                                </li>
                                <li>
                                    <a href=@Url.Action("Index", "ToDos")><i class="fa fa-check-square-o"></i> ToDoリスト </a>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Job</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-bar-chart"></i> 取引管理 <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href=@Url.Action("Index", "Deals")>取引一覧</a></li>
                                        <li><a href=@Url.Action("Create", "Deals") class="">取引登録</a></li>
                                        <li><a href=@Url.Action("Report", "Deals")>レポート</a></li>
                                        <li><a href=@Url.Action("Seikyu", "Deals")>請求額照会</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Other</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-external-link"></i> 外部リンク <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        @if (Session["WEB_LINKS"] != null)
                                        {
                                            List<WebLink> links = (List<WebLink>) Session["WEB_LINKS"];
                                            foreach (WebLink link in links)
                                            {
                                                <li><a href=@link.Url target="_blank">@link.Name</a></li>
                                            }
                                        }
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Admin</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-users"></i> アカウント管理 <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href=@Url.Action("Index", "Account")>アカウント一覧</a></li>
                                        <li><a href=@Url.Action("Register", "Account")>アカウント登録</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen" onclick="this.maximize();">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        @Html.Partial("_LoginPartial")
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                @RenderBody()
            </div>

            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    © 2017 - Q's works
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)
</body>
</html>