QsAdmin/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QsAdmin.Models;

namespace QsAdmin.Controllers
{
    public class CustomersController : QsAdminController
    {

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerId,CustomerName,CustomerShortName,GroupName,CompanyName,TransferName,ClosingDate,TaxWithholdingFlag,Memo,DeleteFlag")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerId,CustomerName,CustomerShortName,GroupName,CompanyName,TransferName,ClosingDate,TaxWithholdingFlag,Memo,DeleteFlag")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QsAdmin/Controllers/DealCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QsAdmin.Models;

namespace QsAdmin.Controllers
{
    public class DealCategoriesController : QsAdminController
    {

        // GET: DealCategories
        public ActionResult Index()
        {
            return View(db.DealCategories.ToList());
        }

        // GET: DealCategories/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealCategory dealCategory = db.DealCategories.Find(id);
            if (dealCategory == null)
            {
                return HttpNotFound();
            }
            return View(dealCategory);
        }

        // GET: DealCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DealCategories/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DealCategoryId,DealCategoryName,BasicPrice")] DealCategory dealCategory)
        {
            if (ModelState.IsValid)
            {
                db.DealCategories.Add(dealCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dealCategory);
        }

        // GET: DealCategories/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealCategory dealCategory = db.DealCategories.Find(id);
            if (dealCategory == null)
            {
                return HttpNotFound();
            }
            return View(dealCategory);
        }

        // POST: DealCategories/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DealCategoryId,DealCategoryName,BasicPrice")] DealCategory dealCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dealCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dealCategory);
        }

        // GET: DealCategories/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DealCategory dealCategory = db.DealCategories.Find(id);
            if (dealCategory == null)
            {
                return HttpNotFound();
            }
            return View(dealCategory);
        }

        // POST: DealCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DealCategory dealCategory = db.DealCategories.Find(id);
            db.DealCategories.Remove(dealCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QsAdmin/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QsAdmin.Models;
using Microsoft.AspNet.Identity;
using System.Text;
using WebGrease.Css.Extensions;

namespace QsAdmin.Controllers
{
    public class DealsController : QsAdminController
    {
        private DealManager m = new DealManager();

        public ActionResult Index(int? seachFlag, int? year, int? month, bool? kanryo, string keyword, int? endDealId)
        {
            SeachCondition condition = new SeachCondition(year, month, kanryo, keyword);

            if (Session["DealSearch"] != null && seachFlag == null)
            {
                condition = (SeachCondition)Session["DealSearch"];
            }

            // 完了
            m.EndDeal(endDealId);

            // 取引リスト取得
            List<DealViewModel> deals = m.GetDealList(condition);
            Session["DealSearch"] = condition;

            ViewBag.year = m.GetYearOptions(condition.Year);
            ViewBag.month = m.GetMonthOptions(condition.Month);
            ViewBag.keyword = condition.Keyword;
            ViewBag.Kanryo = condition.Kanryo;

            return View(deals.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        private List<SelectListItem> getCustomerList(string id)
        {
            var list = from c in db.Customers
                       where c.DeleteFlag == false
                       orderby c.GroupName
                       select new SelectListItem
                       {
                           Value = c.CustomerId,
                           Text = c.CustomerShortName,
                           Selected = id != null ? c.CustomerId == id : false
                       };

            return list.ToList();
        }

        public ActionResult Create()
        {
            ViewBag.CustomerId = getCustomerList(null);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName");

            Deal deal = new Deal();

            deal.ReceptionDate = DateTime.Now;
            // 単価は現状ほぼ300円
            deal.Price = 300;
            deal.Number = 0;

            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                deal.AccountId = User.Identity.GetUserId();

                db.Deals.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);

            // 完了日時と計上年月をセット
            if (deal.EndDate == null)
            {
                deal.EndDate = DateTime.Now;
                deal.KeijoTsuki = deal.GetKeijoTsuki();
            }

            if (deal == null)
            {
                return HttpNotFound();
            }

            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName", deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Copy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);

            if (string.IsNullOrEmpty(deal.KeijoTsuki))
            {
                deal.KeijoTsuki = deal.GetKeijoTsuki();
            }

            if (deal == null)
            {
                return HttpNotFound();
            }

            ViewBag.AccountId = new SelectList(db.Users, "Id", "Email", deal.AccountId);
            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Copy([Bind(Include = "Id,CustomerId,DealCategoryId,AccountId,Tag,Price,Number,Memo,ReceptionDate,EndDate,KeijoTsuki")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                db.Deals.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountId = new SelectList(db.Users, "Id", "Email", deal.AccountId);
            ViewBag.CustomerId = getCustomerList(deal.CustomerId);
            ViewBag.DealCategoryId = new SelectList(db.DealCategories, "DealCategoryId", "DealCategoryName", deal.DealCategoryId);
            return View(deal);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deal deal = db.Deals.Find(id);
            if (deal == null)
            {
                return HttpNotFound();
            }
            return View(deal);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Deal deal = db.Deals.Find(id);
            db.Deals.Remove(deal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 月別売上表示
        /// </summary>
        /// <returns></returns>
        public ActionResult Report(string year, string month, int? range)
        {
            if (string.IsNullOrEmpty(year))
            {
                year = DateTime.Now.Year.ToString();
            }
            if (string.IsNullOrEmpty(month))
            {
                month = DateTime.Now.Month.ToString();
            }
            if (range == null)
            {
                range = 12;
            }

            string date = year + "/" + month + "/01";
            DateTime dateEnd = DateTime.Parse(date);
            DateTime dateStart = DateTime.Parse(date).AddMonths(((int)range - 1) * -1);

            var reports = db.Database.SqlQuery<ReportViewModel>(""
                + " select"
                + "   a.KeijoTsuki as Nengetsu,"
                + "   sum(a.Number) as Number,"
                + "   sum(a.Price * a.Number) as HontaiGaku,"
                + "   sum((a.Price * a.Number) * 0.08) as ShohizeiGaku,"
                + "   sum((a.Price * a.Number) + ((a.Price * a.Number) * 0.08)) as Uriage"
                + " from"
                + "   Deals a"
                + " where"
                + "   a.KeijoTsuki >= '" + dateStart.ToString("yyyy/MM") + "'"
                + "   and a.KeijoTsuki <= '" + dateEnd.ToString("yyyy/MM") + "'"
                + " group by"
                + "   a.KeijoTsuki"
                + " order by"
                + "   a.KeijoTsuki"
                );

            List<ReportViewModel> reportView = reports.ToList();

            ViewBag.year = m.GetYearOptions(int.Parse(year));
            ViewBag.month = m.GetMonthOptions(int.Parse(month));

            return View(reportView);
        }



        public ActionResult Seikyu(string year, string month)
        {
            if (string.IsNullOrEmpty(year))
            {
                year = DateTime.Now.Year.ToString();
            }
            if (string.IsNullOrEmpty(month))
            {
                month = DateTime.Now.Month.ToString();
            }

            ViewBag._Year = year;
            ViewBag._Month = month;

            var seikyus = FindSeikyuView(year, month);

            ViewBag.year = m.GetYearOptions(DateTime.Now.Year);
            ViewBag.month = m.GetMonthOptions(DateTime.Now.Month);

            return View(seikyus);
        }

        public IEnumerable<SeikyuViewModel> FindSeikyuView(string year, string month)
        {
            string pYear = DateTime.Now.Year.ToString();
            string pMonth = DateTime.Now.Month.ToString();

            if (!string.IsNullOrEmpty(year))
            {
                pYear = year;
            }
            if (!string.IsNullOrEmpty(month))
            {
                pMonth = month;
            }

            string keijoTsuki = pYear + "/" + pMonth.PadLeft(2, '0');

            var seikyus = db.Database.SqlQuery<SeikyuViewModel>(""
                + " select"

QsAdmin/Views/Deals/Copy.cshtml
@model QsAdmin.Models.Deal

@{
    ViewBag.Title = "取引管理";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>取引管理 <small>登録</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @Html.Partial("_DealsForm")

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="submit" value="登録" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
                
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QsAdmin/Views/Deals/Index.cshtml
@model IEnumerable<QsAdmin.Models.DealViewModel>

@{
    ViewBag.Title = "取引管理";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>取引管理 <small>検索・一覧</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li title="取引登録">
                        <a href=@Url.Action("Create", "Deals") class="dropdown-toggle"><i class="fa fa-plus"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href=@Url.Action("Index", "Customers") class="dropdown-toggle">取引先登録</a>
                            </li>
                            <li>
                                <a href=@Url.Action("Index", "DealCategories") class="dropdown-toggle">取引区分登録</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-toolbar">

                    @using (Html.BeginForm("Index", "Deals", FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <input type="hidden" name="seachFlag" value="1"/>
                        @Html.Label("year", "計上年月:", new { @class = "control-label" })
                        @Html.DropDownList("year", null, "", htmlAttributes: new { @class = "form-control dateTxt" })
                        @Html.Label("month", "/", new { })
                        @Html.DropDownList("month", null, "", htmlAttributes: new { @class = "form-control dateTxt" })
                        @Html.Label("keyword", "キーワード:", new { @class = "control-label" })
                        @Html.TextBox("keyword", (string)ViewBag.keyword, new { @class = "form-control keyword" })
                        @Html.Label("kanryo", "完了分を含む:", new { @class = "control-label" })
                        @Html.CheckBox("kanryo")
                        <div class="pull-right">
                            <input type="submit" value="検索" class="btn btn-success searchBtn" />
                        </div>
                    }

                </div>

                <hr />

                @using (Html.BeginForm("Index", "Deals", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="sshortCol"></th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.ReceptionDate)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.DealCategoryName)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Tag)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.CustomerName)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Number)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.ExistsMemo)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.EndDate)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.KeijoTsuki)</th>
                                <th class="column-title no-link last">
                                    <span class="nobr">Action</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                string style = item.IsKanryo() ? "kanryo" : "";

                                <tr class=@style>
                                    <td class="center">
                                        @if (!item.IsKanryo())
                                        {
                                            <button type="submit" name="endDealId" value=@item.Id class="btn btn-mini" title="完了にする"><i class="fa fa-check"></i></button>
                                        }
                                        else
                                        {
                                            <span>完了</span>
                                        }
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.ReceptionDate)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.DealCategoryName)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.Tag)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.CustomerName)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.Number)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.ExistsMemo)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.EndDate)
                                    </td>
                                    <td class="">
                                        @Html.DisplayFor(modelItem => item.KeijoTsuki)
                                    </td>
                                    <td class="last">
                                        <a href="@Url.Action("Details", "Deals", new { id = item.Id })">View</a> |
                                        <a href="@Url.Action("Edit", "Deals", new { id = item.Id })">Edit</a> |
                                        <a href="@Url.Action("Copy", "Deals", new { id = item.Id })">Copy</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
</div>

QsAdmin/Views/Deals/Report.cshtml
@model IEnumerable<QsAdmin.Models.ReportViewModel>

@{
    ViewBag.Title = "取引管理";
}

<div class="row">
    <div class="col-md-12 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>取引管理 <small>月別売上高（グラフ）</small></h2>
                <ul class="nav navbar-right panel_toolbox"></ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-toolbar">

                    @using (Html.BeginForm("Report", "Deals", FormMethod.Get, new { @class = "form-inline" }))
                    {
                        @Html.Label("year", "計上年月:", new { @class = "control-label" })
                        @Html.DropDownList("year", null, "", htmlAttributes: new { @class = "form-control dateTxt" })
                        @Html.Label("month", "/", new { })
                        @Html.DropDownList("month", null, "", htmlAttributes: new { @class = "form-control dateTxt" })
                        @Html.Label("month", "まで", new { })
                        @Html.TextBox("range", 12, new { @class = "form-control dateTxt" })
                        @Html.Label("month", "ヵ月分", new { })
                        <div class="pull-right">
                            <input type="submit" value="検索" class="btn btn-success searchBtn" />
                        </div>
                    }
                </div>

                <hr />
                <div class="chart-container" style="position: relative; max-width: 1000px;">
                    <canvas id="uriageChart" ></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>取引管理 <small>月別売上高（一覧）</small></h2>
                <ul class="nav navbar-right panel_toolbox"></ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="column-title">@Html.DisplayNameFor(model => model.Nengetsu)</th>
                            <th class="column-title">@Html.DisplayNameFor(model => model.Number)</th>
                            <th class="column-title">@Html.DisplayNameFor(model => model.HontaiGaku)</th>
                            <th class="column-title">@Html.DisplayNameFor(model => model.ShohizeiGaku)</th>
                            <th class="column-title">@Html.DisplayNameFor(model => model.Uriage)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int sumNumber = 0;
                            int sumHontaiGaku = 0;
                            decimal sumShohizei = 0;
                            decimal sumUriage = 0;
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="">
                                    @Html.DisplayFor(modelItem => item.Nengetsu)
                                </td>
                                <td class="">
                                    @Html.DisplayFor(modelItem => item.Number)
                                </td>
                                <td class="kingakuCol">
                                    @Html.DisplayFor(modelItem => item.HontaiGaku)
                                </td>
                                <td class="kingakuCol">
                                    @Html.DisplayFor(modelItem => item.ShohizeiGaku)
                                </td>
                                <td class="kingakuCol">
                                    @Html.DisplayFor(modelItem => item.Uriage)
                                </td>
                            </tr>

                            sumNumber += item.Number;
                            sumHontaiGaku += item.HontaiGaku;
                            sumShohizei += item.ShohizeiGaku;
                            sumUriage += item.Uriage;
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="">合計</td>
                            <td class="">@sumNumber</td>
                            <td class="kingakuCol">@sumHontaiGaku.ToString("#,0")</td>
                            <td class="kingakuCol">@sumShohizei.ToString("#,0")</td>
                            <td class="kingakuCol">@sumUriage.ToString("#,0")</td>
                        </tr>
                    </tfoot>
                </table>

            </div>
        </div>
    </div>
</div>

@{
    string months = "";
    string uriages = "";
}

@foreach (var item in Model)
{
    months += "'" + item.Nengetsu + "',";
    uriages += item.Uriage + ",";
}

@section Scripts {
    <!-- Chart.js -->
    <script src="~/Content/vendors/Chart.js/dist/Chart.min.js"></script>

    <script type="text/javascript">
        if ($('#uriageChart').length) {

            var ctx = document.getElementById("uriageChart");
            var mybarChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [@Html.Raw(months)],
                    datasets: [{
                        label: '売上',
                        backgroundColor: "#26B99A",
                        data: [@Html.Raw(uriages)]
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    },
                    layout: {
                        responsive: false
                    }
                }
            });

        }
    </script>
}